/*
 * This file is generated by jOOQ.
 */
package com.example.travel.database.schema.tables;


import com.example.travel.database.schema.Indexes;
import com.example.travel.database.schema.Keys;
import com.example.travel.database.schema.Sql4458432;
import com.example.travel.database.schema.tables.records.HotelRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Hotel extends TableImpl<HotelRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>sql4458432.hotel</code>
     */
    public static final Hotel HOTEL = new Hotel();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<HotelRecord> getRecordType() {
        return HotelRecord.class;
    }

    /**
     * The column <code>sql4458432.hotel.hotel_id</code>.
     */
    public final TableField<HotelRecord, Integer> HOTEL_ID = createField(DSL.name("hotel_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>sql4458432.hotel.name</code>.
     */
    public final TableField<HotelRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>sql4458432.hotel.country_no</code>.
     */
    public final TableField<HotelRecord, Integer> COUNTRY_NO = createField(DSL.name("country_no"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>sql4458432.hotel.details</code>.
     */
    public final TableField<HotelRecord, String> DETAILS = createField(DSL.name("details"), SQLDataType.VARCHAR(45), this, "");

    private Hotel(Name alias, Table<HotelRecord> aliased) {
        this(alias, aliased, null);
    }

    private Hotel(Name alias, Table<HotelRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>sql4458432.hotel</code> table reference
     */
    public Hotel(String alias) {
        this(DSL.name(alias), HOTEL);
    }

    /**
     * Create an aliased <code>sql4458432.hotel</code> table reference
     */
    public Hotel(Name alias) {
        this(alias, HOTEL);
    }

    /**
     * Create a <code>sql4458432.hotel</code> table reference
     */
    public Hotel() {
        this(DSL.name("hotel"), null);
    }

    public <O extends Record> Hotel(Table<O> child, ForeignKey<O, HotelRecord> key) {
        super(child, key, HOTEL);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Sql4458432.SQL4458432;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.HOTEL_COUNTRYID_IDX);
    }

    @Override
    public Identity<HotelRecord, Integer> getIdentity() {
        return (Identity<HotelRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<HotelRecord> getPrimaryKey() {
        return Keys.KEY_HOTEL_PRIMARY;
    }

    @Override
    public List<ForeignKey<HotelRecord, ?>> getReferences() {
        return Arrays.asList(Keys.COUNTRYID);
    }

    private transient Country _country;

    public Country country() {
        if (_country == null)
            _country = new Country(this, Keys.COUNTRYID);

        return _country;
    }

    @Override
    public Hotel as(String alias) {
        return new Hotel(DSL.name(alias), this);
    }

    @Override
    public Hotel as(Name alias) {
        return new Hotel(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Hotel rename(String name) {
        return new Hotel(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Hotel rename(Name name) {
        return new Hotel(name, null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, Integer, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }
}
