/*
 * This file is generated by jOOQ.
 */
package com.example.travel.database.schema.tables;


import com.example.travel.database.schema.Keys;
import com.example.travel.database.schema.Sql4458432;
import com.example.travel.database.schema.tables.records.NutritionRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Nutrition extends TableImpl<NutritionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>sql4458432.nutrition</code>
     */
    public static final Nutrition NUTRITION = new Nutrition();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<NutritionRecord> getRecordType() {
        return NutritionRecord.class;
    }

    /**
     * The column <code>sql4458432.nutrition.nutrition_id</code>.
     */
    public final TableField<NutritionRecord, Integer> NUTRITION_ID = createField(DSL.name("nutrition_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>sql4458432.nutrition.name</code>.
     */
    public final TableField<NutritionRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    private Nutrition(Name alias, Table<NutritionRecord> aliased) {
        this(alias, aliased, null);
    }

    private Nutrition(Name alias, Table<NutritionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>sql4458432.nutrition</code> table reference
     */
    public Nutrition(String alias) {
        this(DSL.name(alias), NUTRITION);
    }

    /**
     * Create an aliased <code>sql4458432.nutrition</code> table reference
     */
    public Nutrition(Name alias) {
        this(alias, NUTRITION);
    }

    /**
     * Create a <code>sql4458432.nutrition</code> table reference
     */
    public Nutrition() {
        this(DSL.name("nutrition"), null);
    }

    public <O extends Record> Nutrition(Table<O> child, ForeignKey<O, NutritionRecord> key) {
        super(child, key, NUTRITION);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Sql4458432.SQL4458432;
    }

    @Override
    public Identity<NutritionRecord, Integer> getIdentity() {
        return (Identity<NutritionRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<NutritionRecord> getPrimaryKey() {
        return Keys.KEY_NUTRITION_PRIMARY;
    }

    @Override
    public Nutrition as(String alias) {
        return new Nutrition(DSL.name(alias), this);
    }

    @Override
    public Nutrition as(Name alias) {
        return new Nutrition(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Nutrition rename(String name) {
        return new Nutrition(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Nutrition rename(Name name) {
        return new Nutrition(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
