/*
 * This file is generated by jOOQ.
 */
package com.example.travel.database.schema.tables;


import com.example.travel.database.schema.Keys;
import com.example.travel.database.schema.Sql4458432;
import com.example.travel.database.schema.tables.records.TravelTypeRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TravelType extends TableImpl<TravelTypeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>sql4458432.travel_type</code>
     */
    public static final TravelType TRAVEL_TYPE = new TravelType();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TravelTypeRecord> getRecordType() {
        return TravelTypeRecord.class;
    }

    /**
     * The column <code>sql4458432.travel_type.type_id</code>.
     */
    public final TableField<TravelTypeRecord, Integer> TYPE_ID = createField(DSL.name("type_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>sql4458432.travel_type.name</code>.
     */
    public final TableField<TravelTypeRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(45).nullable(false), this, "");

    private TravelType(Name alias, Table<TravelTypeRecord> aliased) {
        this(alias, aliased, null);
    }

    private TravelType(Name alias, Table<TravelTypeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>sql4458432.travel_type</code> table reference
     */
    public TravelType(String alias) {
        this(DSL.name(alias), TRAVEL_TYPE);
    }

    /**
     * Create an aliased <code>sql4458432.travel_type</code> table reference
     */
    public TravelType(Name alias) {
        this(alias, TRAVEL_TYPE);
    }

    /**
     * Create a <code>sql4458432.travel_type</code> table reference
     */
    public TravelType() {
        this(DSL.name("travel_type"), null);
    }

    public <O extends Record> TravelType(Table<O> child, ForeignKey<O, TravelTypeRecord> key) {
        super(child, key, TRAVEL_TYPE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Sql4458432.SQL4458432;
    }

    @Override
    public Identity<TravelTypeRecord, Integer> getIdentity() {
        return (Identity<TravelTypeRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<TravelTypeRecord> getPrimaryKey() {
        return Keys.KEY_TRAVEL_TYPE_PRIMARY;
    }

    @Override
    public TravelType as(String alias) {
        return new TravelType(DSL.name(alias), this);
    }

    @Override
    public TravelType as(Name alias) {
        return new TravelType(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TravelType rename(String name) {
        return new TravelType(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TravelType rename(Name name) {
        return new TravelType(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
