/*
 * This file is generated by jOOQ.
 */
package com.example.travel.database.schema;


import com.example.travel.database.schema.tables.Hotel;
import com.example.travel.database.schema.tables.Travel;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in sql4458432.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index HOTEL_COUNTRYID_IDX = Internal.createIndex(DSL.name("countryID_idx"), Hotel.HOTEL, new OrderField[] { Hotel.HOTEL.COUNTRY_NO }, false);
    public static final Index TRAVEL_COUNTRYID_IDX = Internal.createIndex(DSL.name("countryID_idx"), Travel.TRAVEL, new OrderField[] { Travel.TRAVEL.COUNTRY_ID }, false);
    public static final Index TRAVEL_CUSTOMERID_IDX = Internal.createIndex(DSL.name("customerID_idx"), Travel.TRAVEL, new OrderField[] { Travel.TRAVEL.CUSTOMER_ID }, false);
    public static final Index TRAVEL_HOTELID_IDX = Internal.createIndex(DSL.name("hotelID_idx"), Travel.TRAVEL, new OrderField[] { Travel.TRAVEL.HOTEL_ID }, false);
    public static final Index TRAVEL_NUTRITIONID_IDX = Internal.createIndex(DSL.name("nutritionID_idx"), Travel.TRAVEL, new OrderField[] { Travel.TRAVEL.NUTRITION_ID }, false);
    public static final Index TRAVEL_TRANSPORTID_IDX = Internal.createIndex(DSL.name("transportID_idx"), Travel.TRAVEL, new OrderField[] { Travel.TRAVEL.TRANSPORT_ID }, false);
    public static final Index TRAVEL_TYPEID_IDX = Internal.createIndex(DSL.name("typeID_idx"), Travel.TRAVEL, new OrderField[] { Travel.TRAVEL.TYPE_ID }, false);
    public static final Index TRAVEL_USERID_IDX = Internal.createIndex(DSL.name("userID_idx"), Travel.TRAVEL, new OrderField[] { Travel.TRAVEL.USER_ID }, false);
}
