/*
 * This file is generated by jOOQ.
 */
package com.example.travel.database.schema;


import com.example.travel.database.schema.tables.Country;
import com.example.travel.database.schema.tables.Customer;
import com.example.travel.database.schema.tables.Hotel;
import com.example.travel.database.schema.tables.Nutrition;
import com.example.travel.database.schema.tables.Transport;
import com.example.travel.database.schema.tables.Travel;
import com.example.travel.database.schema.tables.TravelType;
import com.example.travel.database.schema.tables.UserAccount;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sql4458432 extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>sql4458432</code>
     */
    public static final Sql4458432 SQL4458432 = new Sql4458432();

    /**
     * The table <code>sql4458432.country</code>.
     */
    public final Country COUNTRY = Country.COUNTRY;

    /**
     * The table <code>sql4458432.customer</code>.
     */
    public final Customer CUSTOMER = Customer.CUSTOMER;

    /**
     * The table <code>sql4458432.hotel</code>.
     */
    public final Hotel HOTEL = Hotel.HOTEL;

    /**
     * The table <code>sql4458432.nutrition</code>.
     */
    public final Nutrition NUTRITION = Nutrition.NUTRITION;

    /**
     * The table <code>sql4458432.transport</code>.
     */
    public final Transport TRANSPORT = Transport.TRANSPORT;

    /**
     * The table <code>sql4458432.travel</code>.
     */
    public final Travel TRAVEL = Travel.TRAVEL;

    /**
     * The table <code>sql4458432.travel_type</code>.
     */
    public final TravelType TRAVEL_TYPE = TravelType.TRAVEL_TYPE;

    /**
     * The table <code>sql4458432.user_account</code>.
     */
    public final UserAccount USER_ACCOUNT = UserAccount.USER_ACCOUNT;

    /**
     * No further instances allowed
     */
    private Sql4458432() {
        super("sql4458432", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Country.COUNTRY,
            Customer.CUSTOMER,
            Hotel.HOTEL,
            Nutrition.NUTRITION,
            Transport.TRANSPORT,
            Travel.TRAVEL,
            TravelType.TRAVEL_TYPE,
            UserAccount.USER_ACCOUNT
        );
    }
}
