/*
 * This file is generated by jOOQ.
 */
package com.example.travel.database.schema;


import com.example.travel.database.schema.tables.UserAccount;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TravelAgency extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>travel_agency</code>
     */
    public static final TravelAgency TRAVEL_AGENCY = new TravelAgency();

    /**
     * The table <code>travel_agency.user_account</code>.
     */
    public final UserAccount USER_ACCOUNT = UserAccount.USER_ACCOUNT;

    /**
     * No further instances allowed
     */
    private TravelAgency() {
        super("travel_agency", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            UserAccount.USER_ACCOUNT
        );
    }
}
