/*
 * This file is generated by jOOQ.
 */
package com.example.travel.database.schema.tables.records;


import com.example.travel.database.schema.tables.Customer;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CustomerRecord extends UpdatableRecordImpl<CustomerRecord> implements Record5<Integer, String, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sql4458432.customer.customer_id</code>.
     */
    public void setCustomerId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>sql4458432.customer.customer_id</code>.
     */
    public Integer getCustomerId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>sql4458432.customer.firstname</code>.
     */
    public void setFirstname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>sql4458432.customer.firstname</code>.
     */
    public String getFirstname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>sql4458432.customer.lastname</code>.
     */
    public void setLastname(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>sql4458432.customer.lastname</code>.
     */
    public String getLastname() {
        return (String) get(2);
    }

    /**
     * Setter for <code>sql4458432.customer.email</code>.
     */
    public void setEmail(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>sql4458432.customer.email</code>.
     */
    public String getEmail() {
        return (String) get(3);
    }

    /**
     * Setter for <code>sql4458432.customer.passportcode</code>.
     */
    public void setPassportcode(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>sql4458432.customer.passportcode</code>.
     */
    public String getPassportcode() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, String, String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, String, String, String, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Customer.CUSTOMER.CUSTOMER_ID;
    }

    @Override
    public Field<String> field2() {
        return Customer.CUSTOMER.FIRSTNAME;
    }

    @Override
    public Field<String> field3() {
        return Customer.CUSTOMER.LASTNAME;
    }

    @Override
    public Field<String> field4() {
        return Customer.CUSTOMER.EMAIL;
    }

    @Override
    public Field<String> field5() {
        return Customer.CUSTOMER.PASSPORTCODE;
    }

    @Override
    public Integer component1() {
        return getCustomerId();
    }

    @Override
    public String component2() {
        return getFirstname();
    }

    @Override
    public String component3() {
        return getLastname();
    }

    @Override
    public String component4() {
        return getEmail();
    }

    @Override
    public String component5() {
        return getPassportcode();
    }

    @Override
    public Integer value1() {
        return getCustomerId();
    }

    @Override
    public String value2() {
        return getFirstname();
    }

    @Override
    public String value3() {
        return getLastname();
    }

    @Override
    public String value4() {
        return getEmail();
    }

    @Override
    public String value5() {
        return getPassportcode();
    }

    @Override
    public CustomerRecord value1(Integer value) {
        setCustomerId(value);
        return this;
    }

    @Override
    public CustomerRecord value2(String value) {
        setFirstname(value);
        return this;
    }

    @Override
    public CustomerRecord value3(String value) {
        setLastname(value);
        return this;
    }

    @Override
    public CustomerRecord value4(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public CustomerRecord value5(String value) {
        setPassportcode(value);
        return this;
    }

    @Override
    public CustomerRecord values(Integer value1, String value2, String value3, String value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CustomerRecord
     */
    public CustomerRecord() {
        super(Customer.CUSTOMER);
    }

    /**
     * Create a detached, initialised CustomerRecord
     */
    public CustomerRecord(Integer customerId, String firstname, String lastname, String email, String passportcode) {
        super(Customer.CUSTOMER);

        setCustomerId(customerId);
        setFirstname(firstname);
        setLastname(lastname);
        setEmail(email);
        setPassportcode(passportcode);
    }
}
