/*
 * This file is generated by jOOQ.
 */
package com.example.travel.database.schema.tables.records;


import com.example.travel.database.schema.tables.Hotel;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HotelRecord extends UpdatableRecordImpl<HotelRecord> implements Record4<Integer, String, Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sql4458432.hotel.hotel_id</code>.
     */
    public void setHotelId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>sql4458432.hotel.hotel_id</code>.
     */
    public Integer getHotelId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>sql4458432.hotel.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>sql4458432.hotel.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>sql4458432.hotel.country_no</code>.
     */
    public void setCountryNo(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>sql4458432.hotel.country_no</code>.
     */
    public Integer getCountryNo() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>sql4458432.hotel.details</code>.
     */
    public void setDetails(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>sql4458432.hotel.details</code>.
     */
    public String getDetails() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, Integer, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, String, Integer, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Hotel.HOTEL.HOTEL_ID;
    }

    @Override
    public Field<String> field2() {
        return Hotel.HOTEL.NAME;
    }

    @Override
    public Field<Integer> field3() {
        return Hotel.HOTEL.COUNTRY_NO;
    }

    @Override
    public Field<String> field4() {
        return Hotel.HOTEL.DETAILS;
    }

    @Override
    public Integer component1() {
        return getHotelId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Integer component3() {
        return getCountryNo();
    }

    @Override
    public String component4() {
        return getDetails();
    }

    @Override
    public Integer value1() {
        return getHotelId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public Integer value3() {
        return getCountryNo();
    }

    @Override
    public String value4() {
        return getDetails();
    }

    @Override
    public HotelRecord value1(Integer value) {
        setHotelId(value);
        return this;
    }

    @Override
    public HotelRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public HotelRecord value3(Integer value) {
        setCountryNo(value);
        return this;
    }

    @Override
    public HotelRecord value4(String value) {
        setDetails(value);
        return this;
    }

    @Override
    public HotelRecord values(Integer value1, String value2, Integer value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached HotelRecord
     */
    public HotelRecord() {
        super(Hotel.HOTEL);
    }

    /**
     * Create a detached, initialised HotelRecord
     */
    public HotelRecord(Integer hotelId, String name, Integer countryNo, String details) {
        super(Hotel.HOTEL);

        setHotelId(hotelId);
        setName(name);
        setCountryNo(countryNo);
        setDetails(details);
    }
}
