/*
 * This file is generated by jOOQ.
 */
package com.example.travel.database.schema.tables.records;


import com.example.travel.database.schema.tables.Transport;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TransportRecord extends UpdatableRecordImpl<TransportRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>sql4458432.transport.transport_id</code>.
     */
    public void setTransportId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>sql4458432.transport.transport_id</code>.
     */
    public Integer getTransportId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>sql4458432.transport.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>sql4458432.transport.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Transport.TRANSPORT.TRANSPORT_ID;
    }

    @Override
    public Field<String> field2() {
        return Transport.TRANSPORT.NAME;
    }

    @Override
    public Integer component1() {
        return getTransportId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Integer value1() {
        return getTransportId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public TransportRecord value1(Integer value) {
        setTransportId(value);
        return this;
    }

    @Override
    public TransportRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public TransportRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TransportRecord
     */
    public TransportRecord() {
        super(Transport.TRANSPORT);
    }

    /**
     * Create a detached, initialised TransportRecord
     */
    public TransportRecord(Integer transportId, String name) {
        super(Transport.TRANSPORT);

        setTransportId(transportId);
        setName(name);
    }
}
