/*
 * This file is generated by jOOQ.
 */
package com.example.travel.database.schema.tables.records;


import com.example.travel.database.schema.tables.UserAccount;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserAccountRecord extends UpdatableRecordImpl<UserAccountRecord> implements Record5<Integer, String, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>travel_agency.user_account.account_id</code>.
     */
    public void setAccountId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>travel_agency.user_account.account_id</code>.
     */
    public Integer getAccountId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>travel_agency.user_account.firstname</code>.
     */
    public void setFirstname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>travel_agency.user_account.firstname</code>.
     */
    public String getFirstname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>travel_agency.user_account.lastname</code>.
     */
    public void setLastname(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>travel_agency.user_account.lastname</code>.
     */
    public String getLastname() {
        return (String) get(2);
    }

    /**
     * Setter for <code>travel_agency.user_account.username</code>.
     */
    public void setUsername(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>travel_agency.user_account.username</code>.
     */
    public String getUsername() {
        return (String) get(3);
    }

    /**
     * Setter for <code>travel_agency.user_account.password</code>.
     */
    public void setPassword(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>travel_agency.user_account.password</code>.
     */
    public String getPassword() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, String, String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, String, String, String, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return UserAccount.USER_ACCOUNT.ACCOUNT_ID;
    }

    @Override
    public Field<String> field2() {
        return UserAccount.USER_ACCOUNT.FIRSTNAME;
    }

    @Override
    public Field<String> field3() {
        return UserAccount.USER_ACCOUNT.LASTNAME;
    }

    @Override
    public Field<String> field4() {
        return UserAccount.USER_ACCOUNT.USERNAME;
    }

    @Override
    public Field<String> field5() {
        return UserAccount.USER_ACCOUNT.PASSWORD;
    }

    @Override
    public Integer component1() {
        return getAccountId();
    }

    @Override
    public String component2() {
        return getFirstname();
    }

    @Override
    public String component3() {
        return getLastname();
    }

    @Override
    public String component4() {
        return getUsername();
    }

    @Override
    public String component5() {
        return getPassword();
    }

    @Override
    public Integer value1() {
        return getAccountId();
    }

    @Override
    public String value2() {
        return getFirstname();
    }

    @Override
    public String value3() {
        return getLastname();
    }

    @Override
    public String value4() {
        return getUsername();
    }

    @Override
    public String value5() {
        return getPassword();
    }

    @Override
    public UserAccountRecord value1(Integer value) {
        setAccountId(value);
        return this;
    }

    @Override
    public UserAccountRecord value2(String value) {
        setFirstname(value);
        return this;
    }

    @Override
    public UserAccountRecord value3(String value) {
        setLastname(value);
        return this;
    }

    @Override
    public UserAccountRecord value4(String value) {
        setUsername(value);
        return this;
    }

    @Override
    public UserAccountRecord value5(String value) {
        setPassword(value);
        return this;
    }

    @Override
    public UserAccountRecord values(Integer value1, String value2, String value3, String value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserAccountRecord
     */
    public UserAccountRecord() {
        super(UserAccount.USER_ACCOUNT);
    }

    /**
     * Create a detached, initialised UserAccountRecord
     */
    public UserAccountRecord(Integer accountId, String firstname, String lastname, String username, String password) {
        super(UserAccount.USER_ACCOUNT);

        setAccountId(accountId);
        setFirstname(firstname);
        setLastname(lastname);
        setUsername(username);
        setPassword(password);
    }
}
